services:
  balanceador:
    build: ./balanceador
    container_name: medical-balanceador
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./balanceador/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - medical-network
    depends_on:
      - api1
      - api2
      - landing
      - tenant1
      - tenant2
      - landlord1
      - landlord2
      - websockets

  mysql:
    image: mysql:8.0
    container_name: medical-mysql
    restart: always
    environment:
      MYSQL_DATABASE: medical_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./services/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - medical-network

  redis:
    image: redis:alpine
    container_name: medical-redis
    restart: always
    volumes:
      - ./services/redis:/data
    networks:
      - medical-network

  api1:
    build:
      context: ./backends/common
    container_name: medical-api-1
    environment:
      - APP_INSTANCE=API_NODE_01
    volumes:
      - ./backends/api-shared:/var/www/medical
      - ./backends/common/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./backends/common/supervisor/master.conf:/etc/supervisor/conf.d/master.conf:ro
    depends_on:
      - mysql
      - redis
    networks:
      - medical-network

  api2:
    build:
      context: ./backends/common
    container_name: medical-api-2
    environment:
      - APP_INSTANCE=API_NODE_02
    volumes:
      - ./backends/api-shared:/var/www/medical
      - ./backends/common/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./backends/common/supervisor/master.conf:/etc/supervisor/conf.d/master.conf:ro
    depends_on:
      - mysql
      - redis
    networks:
      - medical-network

  tenant1:
    build:
      context: ./frontends/common
    container_name: medical-tenant-1
    environment:
      - APP_INSTANCE=TENANT_NODE_01
    volumes:
      - ./frontends/tenant:/var/www/medical
      - ./frontends/common/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./frontends/common/supervisor/master.conf:/etc/supervisor/conf.d/master.conf:ro
    depends_on:
      - mysql
    networks:
      - medical-network

  tenant2:
    build:
      context: ./frontends/common
    container_name: medical-tenant-2
    environment:
      - APP_INSTANCE=TENANT_NODE_02
    volumes:
      - ./frontends/tenant:/var/www/medical
      - ./frontends/common/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./frontends/common/supervisor/master.conf:/etc/supervisor/conf.d/master.conf:ro
    depends_on:
      - mysql
    networks:
      - medical-network

  landlord1:
    build:
      context: ./frontends/common
    container_name: medical-landlord-1
    environment:
      - APP_INSTANCE=LANDLORD_NODE_01
    volumes:
      - ./frontends/landlord:/var/www/medical
      - ./frontends/common/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./frontends/common/supervisor/master.conf:/etc/supervisor/conf.d/master.conf:ro
    depends_on:
      - mysql
    networks:
      - medical-network

  landlord2:
    build:
      context: ./frontends/common
    container_name: medical-landlord-2
    environment:
      - APP_INSTANCE=LANDLORD_NODE_02
    volumes:
      - ./frontends/landlord:/var/www/medical
      - ./frontends/common/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./frontends/common/supervisor/master.conf:/etc/supervisor/conf.d/master.conf:ro
    depends_on:
      - mysql
    networks:
      - medical-network

  landing:
    build:
      context: ./frontends/common
    container_name: medical-landing
    volumes:
      - ./frontends/landing:/var/www/medical
      - ./frontends/common/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./frontends/common/supervisor/master.conf:/etc/supervisor/conf.d/master.conf:ro
    depends_on:
      - mysql
    networks:
      - medical-network

  websockets:
    build:
      context: ./websockets
    container_name: medical-websockets
    volumes:
      - ./websockets/src:/usr/src/app/src
    environment:
      - NODE_ENV=development
    networks:
      - medical-network
    depends_on:
      - redis

  mailhog:
    image: mailhog/mailhog
    container_name: medical-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - medical-network

  minio:
    image: minio/minio
    container_name: medical-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./devtools/minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - medical-network

# --- ESTA PARTE DEBE IR SIN ESPACIOS AL INICIO ---
networks:
  medical-network:
    driver: bridge